import Foundation

// Write the model list of the agent skill and the user guide's API section from the catalog and the benchmarks.
//
//   xcrun swift scripts/agent-docs.swift             rewrite the block between <!-- MODELS_START --> and <!-- MODELS_END -->
//                                                    in Resources/SKILL.md and docs/USAGE.md
//   xcrun swift scripts/agent-docs.swift --check     change nothing; exit 1 and name each file whose block is not the generator's
//   xcrun swift scripts/agent-docs.swift --selftest  check the generator on synthetic data
//   options: --root DIR (the checkout, default the current directory), --benchmarks FILE, --models FILE
//
// One table, identical in both files: model id (what `--model`, `vella select` and the API take), mode, what it is, languages,
// parameters, licence, the tiers offered (named by the format that runs) and the figures of the cell a model first loads on
// (Optimized, 16-bit tier, Fast), from Resources/benchmarks.json. While that file has `figures_pending: true` the figures are `—`.
// Run it after Resources/models.json or Resources/benchmarks.json changes and commit the result;
// Tests/VellaCoreTests/ModelDocsTests runs --check.

typealias JSON = [String: Any]

let startMarker = "<!-- MODELS_START -->"
let endMarker = "<!-- MODELS_END -->"
let files = ["Resources/SKILL.md", "docs/USAGE.md"]
let tiers = ["16", "8", "4"]
let dash = "—"

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data((message + "\n").utf8))
    exit(1)
}

func loadJSON(_ path: String) -> JSON {
    guard let data = FileManager.default.contents(atPath: path), let object = try? JSONSerialization.jsonObject(with: data) as? JSON else {
        fail("cannot read \(path)")
    }
    return object
}

func number(_ value: Double?, _ digits: Int) -> String { value.map { String(format: "%.\(digits)f", $0) } ?? dash }
func double(_ value: Any?) -> Double? { (value as? NSNumber)?.doubleValue }
func isPending(_ bench: JSON) -> Bool { bench["figures_pending"] as? Bool ?? false }
func escaped(_ text: String) -> String { text.replacingOccurrences(of: "|", with: "\\|") }

func dtypeLabel(_ family: JSON, _ tier: String) -> String {
    switch tier {
    case "8": return "int8"
    case "4": return "int4"
    default: return family["native_dtype"] as? String == "float16" ? "fp16" : "bf16"
    }
}

func replaceBlock(_ text: String, _ body: String) -> String? {
    guard text.components(separatedBy: startMarker).count == 2, text.components(separatedBy: endMarker).count == 2,
        let start = text.range(of: startMarker), let end = text.range(of: endMarker), start.upperBound <= end.lowerBound
    else { return nil }
    var block = body
    while block.hasSuffix("\n") { block.removeLast() }
    return String(text[..<start.upperBound]) + "\n" + block + "\n" + String(text[end.lowerBound...])
}

func row(_ family: JSON, _ bench: JSON) -> String {
    let id = family["id"] as? String ?? ""
    var figures: JSON?
    if !isPending(bench) {
        let tier = ((bench["models"] as? JSON)?[id] as? JSON).flatMap { ($0["tiers"] as? JSON)?["16"] as? JSON }
        if let cell = tier?[(tier?["display_cells"] as? [String: String])?["optimized_fast"] ?? "optimized_fast"] as? JSON, cell["measured"] as? JSON != nil { figures = cell }
    }
    let speed = double(figures?["speed_x"])
    let offered = (family["tiers_offered"] as? [String] ?? []).filter { tiers.contains($0) }.sorted { tiers.firstIndex(of: $0)! < tiers.firstIndex(of: $1)! }
    let columns = [
        "`\(id)`", family["mode"] as? String ?? dash, escaped(family["summary"] as? String ?? dash), String((family["languages"] as? [Any])?.count ?? 0),
        family["params"] as? String ?? dash, escaped(family["licence"] as? String ?? dash), offered.map { dtypeLabel(family, $0) }.joined(separator: ", "),
        number(double(figures?["wer"]), 2), speed.map { number($0, 1) + "×" } ?? dash, number(double(figures?["j_per_min"]), 2),
        number(double(figures?["memory_mb"]), 0)
    ]
    return "| " + columns.joined(separator: " | ") + " |"
}

func render(_ models: JSON, _ bench: JSON) -> String {
    var lines = [
        "<!-- Generated by scripts/agent-docs.swift from Resources/models.json and Resources/benchmarks.json. Do not edit between the markers; run the script. -->",
        "", "| Model id | Mode | What it is | Language count | Params | Licence | Tiers offered | English WER % | Speed | J / audio min | Peak RAM MB |",
        "|---|---|---|---|---|---|---|---|---|---|---|"
    ]
    lines += (models["families"] as? [JSON] ?? []).map { row($0, bench) }
    var note =
        "English WER is on the 167 English minutes of v2 (239.7 min total); nine other languages are scored separately. Figures are the Optimized · Fast cell of the 16-bit tier, the cell a model first loads on. Speed is × real time and energy is joules "
        + "per minute of audio on the reference Mac (\(bench["hardware"] as? String ?? dash)); they are not measurements of this Mac. "
        + "Fast enables every kept lever for that model and precision; Exact enables only exact kept levers; Standard enables none. "
        + "Streaming models do not transcribe files. `vella models --json` lists every cell, its measured English WER, speed, energy, peak RAM, measurement provenance or refusal reason, and the source and size. Equal recipes use the canonical measured cell named in `cells[].provenance.display_cell` (`display_cells` in the benchmark file)."
    if isPending(bench) {
        note =
            "Figures pending: the 2.0.0 measurement has not been written into `Resources/benchmarks.json` yet (`figures_pending` is true), "
            + "so no figure is shown. A figure that is not measured is \(dash). " + note
    }
    return (lines + ["", note]).joined(separator: "\n")
}

func run(root: URL, models: JSON, bench: JSON, check: Bool) -> [String] {
    let block = render(models, bench)
    var stale: [String] = []
    for name in files {
        let url = root.appendingPathComponent(name)
        guard let text = try? String(contentsOf: url, encoding: .utf8) else {
            stale.append("\(name): missing")
            continue
        }
        guard let updated = replaceBlock(text, block) else {
            stale.append("\(name): needs exactly one \(startMarker) ... \(endMarker) pair")
            continue
        }
        if updated == text { continue }
        if check {
            stale.append("\(name): generated block is stale")
        } else {
            do { try updated.write(to: url, atomically: true, encoding: .utf8) } catch { fail("cannot write \(name): \(error)") }
            print("wrote \(name)")
        }
    }
    return stale
}

func selfTest() {
    let family: JSON = [
        "id": "demo", "mode": "dictation", "summary": "A demo | with a bar", "languages": ["en", "pl"], "params": "1B", "licence": "MIT",
        "native_dtype": "bfloat16", "tiers_offered": ["8", "16"]
    ]
    let models: JSON = ["families": [family]]
    let cell: JSON = ["wer": 5.5, "speed_x": 123.45, "j_per_min": 4.5, "memory_mb": 1700.4, "measured": ["date": "2026-10-02"] as JSON]
    var bench: JSON = [
        "figures_pending": false, "hardware": "Test Mac",
        "models": ["demo": ["tiers": ["16": ["optimized_fast": cell] as JSON] as JSON] as JSON] as JSON
    ]
    let measured = "| `demo` | dictation | A demo \\| with a bar | 2 | 1B | MIT | bf16, int8 | 5.50 | 123.5× | 4.50 | 1700 |"
    if row(family, bench) != measured { fail("selftest: \(row(family, bench))") }
    bench["figures_pending"] = true
    let pending = "| `demo` | dictation | A demo \\| with a bar | 2 | 1B | MIT | bf16, int8 | — | — | — | — |"
    if row(family, bench) != pending { fail("selftest: \(row(family, bench))") }
    if !render(models, bench).contains("Figures pending") { fail("selftest: no pending line") }
    if replaceBlock("a\n\(startMarker)\nold\n\(endMarker)\nb\n", "new") != "a\n\(startMarker)\nnew\n\(endMarker)\nb\n" { fail("selftest: replaceBlock") }
    print("selftest ok")
}

// MARK: main

let arguments = Array(CommandLine.arguments.dropFirst())
func option(_ name: String) -> String? {
    guard let index = arguments.firstIndex(of: name), index + 1 < arguments.count else { return nil }
    return arguments[index + 1]
}
if arguments.contains("--selftest") {
    selfTest()
    exit(0)
}
let check = arguments.contains("--check")
let root = URL(fileURLWithPath: option("--root") ?? FileManager.default.currentDirectoryPath)
let models = loadJSON(option("--models") ?? root.appendingPathComponent("Resources/models.json").path)
let bench = loadJSON(option("--benchmarks") ?? root.appendingPathComponent("Resources/benchmarks.json").path)
let stale = run(root: root, models: models, bench: bench, check: check)
for line in stale { FileHandle.standardError.write(Data((line + "\n").utf8)) }
if !stale.isEmpty {
    if check { FileHandle.standardError.write(Data("run `xcrun swift scripts/agent-docs.swift` and commit the result\n".utf8)) }
    exit(1)
}
if check { print("SKILL.md and USAGE.md model lists match Resources/models.json and Resources/benchmarks.json") }
